var urlHost = app.getUrlHost();
//on valorise les variables par un script sh lors de déploiement du package front
var urlHostApi = 
var urlHostParam = 

var urls = {
    'urlHttpServer': urlHttpServer,
	
	//# urls goto
    'urlGotoVersements': '/versements',
    'urlGotoVersement': '/versement/{0}',
    'urlGotoVersementControles': '/versement/{0}/controles',
    'urlGotoVersementReglements': '/versement/{0}/reglements',
    'urlGotoTaches': '/taches',
    'urlGotoReglement': '/reglement/{0}',
    'urlAddReglement': '/reglement/add/{0}',
    'urlAddJustficatifRemboursement': '/justificatifRemboursement/add/{0}',
    'urlGotoJustficatifRemboursement': '/justificatifRemboursement/{0}',
    'urlAddAvance': '/avanceContractuel/add',
    'urlGoToAvance': '/avanceContractuel/{0}',
    'urlGotoReglementFixationTaux': '/reglement/{0}/fixationTaux',
    'urlGotoReglementDC': '/reglement/{0}/documentContractuel',
    'urlGotoReglementControles': '/reglement/{0}/controles',
    'urlGotoReglementControlesForceLvl1': '/reglement/{0}/controles?fLvl1=true',
    'urlGotoProjets': '/projets',
    'urlGotoProjetsType': '/projets/{0}/type/{1}',
    'urlAddDocumentContractuel': '/documentContractuel/add',
    'urlGoToDocumentContractuel': '/documentContractuel/{0}',
    'urlGotoAnomalie': '/anomalie/{0}/unitaire',
    'urlGotoAnomalieRajZero': '/anomalie/{0}/raj',
    'urlGotoAnomalieRajDefaut': '/anomalie/{0}/raj-defaut',
    'urlGotoHistoriqueAnomalie': '/historique/anomalie/{0}/unitaire',
    'urlGotoHistoriqueAnomalieRajZero': '/historique/anomalie/{0}/raj',
    'urlGotoHistoriqueAnomalieRajDefaut': '/historique/anomalie/{0}/raj-defaut',
    'urlGotoHistoriqueDossier': '/historique/dossier/{0}',
    'urlGotoHistoriqueDossierRaj': '/historique/dossiersRaj/{0}',
    'urlGotoAvanceContractuelControles': '/avanceContractuel/{0}/controles',
	
	
	//##### BONITA
	
	'urlLogout': urlHost + '/bonita/logoutservice?locale=fr&redirectUrl=',
    'urlGetSession': urlHost + '/bonita/API/system/session/unusedid',
    'urlGetUser': urlHost + '/bonita/API/identity/user/{0}',
    'urlGetGroupUser': urlHost + '/bonita/API/identity/membership?p=0&c=1&f=user_id={0}&d=group_id',
	'urlGetRole': urlHost + '/bonita/API/identity/membership?p=0&c=10&f=user_id={0}&d=role_id',
	
	//##### BONITA BPM / PROCESS
	
	'urlGetPilotageAffectationsBatchDate': urlHostApi + '/bonita/API/bpm/case?p=0&c=1&f=name=BatchCalculAffectationDossier2nd&o=id%20DESC',
	'urlGetTache': urlHost + '/bonita/API/bpm/humanTask?p=0&c=1&f=name=Vérification%20complétude%20dossier&f=state=ready',
    'urlGetTaskByCaseId': urlHost + '/bonita/API/bpm/humanTask?p=0&c=1&f=caseId={0}',
    'urlGetTaskByParentCaseId': urlHost + '/bonita/API/bpm/humanTask?p=0&c=1&f=parentCaseId={0}',
    'urlgetArchivedTask': urlHost + '/bonita/API/bpm/archivedHumanTask?p=0&c=10000&f=caseId={0}',
    'urlGetTaches': urlHost + '/bonita/API/bpm/humanTask?c=10000&p=0&f=state=ready&f=user_id={0}',
    'urlGetTachesByCase': urlHost + '/bonita/API/bpm/humanTask?c=10000&p=0&f=state=ready&f=user_id={0}&f=parentCaseId={1}',
    'urlGetContext': urlHost + '/bonita/API/bpm/userTask/{0}/context',
    'urlGetCasePROPARCO': urlHost + '/bonita/API/bpm/case/{0}',
    'urlGetCaseContextPROPARCO': urlHost + '/bonita/API/bpm/case/{0}/context',
    'urlGetCaseContextAFD': urlHost + '/bonita/API/bpm/archivedCase/{0}/context',
    'urlGetCaseAFD': urlHost + '/bonita/API/bpm/archivedCase?c=1&p=0&f=sourceObjectId={0}',
    'urlTaskExecute': urlHost + '/bonita/API/bpm/userTask/{0}/execution',
    'urlUpdateTask': urlHost + '/bonita/API/bpm/userTask/{0}',
	'urlGetTaskByCriteres': urlHost + '/bonita/API/bpm/activity?c=1&p=0&f=state=failed&f=type=CALL_ACTIVITY&f=parentCaseId={0}',
    'urlGetExecutingTaskByCriteres': urlHost + '/bonita/API/bpm/activity?c=1&p=0&f=state=executing&f=type=CALL_ACTIVITY&f=parentCaseId={0}',
    'urlGetAutomaticTaskByCriteres': urlHost + '/bonita/API/bpm/activity?c=1&p=0&f=state=failed&f=type=AUTOMATIC_TASK&f=parentCaseId={0}',
    'urlUpdateTaskByCaseId': urlHost + '/bonita/API/bpm/activity/{0}',
	'urlControleAgent': urlHost + '/bonita/portal/resource/taskInstance/Ordonnancement/1.0/Controles%20Agent/API/bpm/userTask/{taskId}/execution?assign=true',
	'urlProcessInstanciation': urlHost + '/bonita/API/bpm/process/{0}/instantiation',
    'urlProcessAddVersementAFD': urlHost + '/bonita/API/bpm/process?p=0&f=name=CreerDossierVersementAFD&f=activationState=ENABLED',
    'urlProcessUpdateVersement': urlHost + '/bonita/API/bpm/process?p=0&f=name=UpdateDossierVersement&f=activationState=ENABLED',
    'urlProcessAddReglement': urlHost + '/bonita/API/bpm/process?p=0&f=name=OrdonnancementDossierReglement&f=activationState=ENABLED',
    'urlProcessUpdateReglement': urlHost + '/bonita/API/bpm/process?p=0&f=name=GererDossierReglement&f=activationState=ENABLED',
	'urlProcessExportPdfDDR': urlHost + '/bonita/API/bpm/process?p=0&f=name=ExporterDemandeReglement_PDF&f=activationState=ENABLED',
    'urlProcessAddJustificatif': urlHost + '/bonita/API/bpm/process?p=0&f=name=CreerJustificatif&f=activationState=ENABLED',
    'urlProcessAddFixationTaux': urlHost + '/bonita/API/bpm/process?p=0&f=name=GererDemandeFixationTaux&f=activationState=ENABLED',
    'urlProcessAddVersementPROPARCO': urlHost + '/bonita/API/bpm/process?p=0&f=name=PROOrdonnancementDossierVersement&f=activationState=ENABLED',
    'urlProcessAddCommentaire': urlHost + '/bonita/API/bpm/process?p=0&f=name=GererCommentaires&f=activationState=ENABLED',
    'urlProcessUpdateControles': urlHost + '/bonita/API/bpm/process?p=0&f=name=UpdateControls&f=activationState=ENABLED',
    'urlProcessAddDocContractuel': urlHost + '/bonita/API/bpm/process?p=0&f=name=GererDocumentContractuel&f=activationState=ENABLED',
    'urlProcessUpdateAddAvance': urlHost + '/bonita/API/bpm/process?p=0&f=name=GererAvanceContractuel&f=activationState=ENABLED',
    'urlProcessGererAvanceFigee': urlHost + '/bonita/API/bpm/process?p=0&f=name=GererAvanceFigee&f=activationState=ENABLED',
    'urlProcessGererJustificatifReglement': urlHost + '/bonita/API/bpm/process?p=0&f=name=GererJustificatifReglement&f=activationState=ENABLED',
    'urlProcessGererJustificatifRemboursement': urlHost + '/bonita/API/bpm/process?p=0&f=name=GererRemboursement&f=activationState=ENABLED',
    'urlProcessPROConfirmationPaiementDR': urlHost + '/bonita/API/bpm/process?p=0&f=name=PROConfirmationPaiementDR&f=activationState=ENABLED',
    'urlProcessGererJustificatifAvance': urlHost + '/bonita/API/bpm/process?p=0&f=name=GererJustificatifAvance&f=activationState=ENABLED',
    'urlProcessCreerRubrique': urlHost + '/bonita/API/bpm/process?p=0&f=name=CreerRubrique&f=activationState=ENABLED',
    'urlProcessBatchCalculAffect': urlHost + '/bonita/API/bpm/process?p=0&f=name=BatchCalculAffectationDossier2nd&f=activationState=ENABLED',
    'urlProcessControleSecondNiveau': urlHost + '/bonita/API/bpm/process?p=0&f=name=ControleSecondNiveau&f=activationState=ENABLED',
    'urlProcessUpdateAnomalie': urlHost + '/bonita/API/bpm/process?p=0&f=name=DCVUpdateAnomalie&f=activationState=ENABLED',
    'urlProcessUpdateAvanceRAJDefault': urlHost + '/bonita/API/bpm/process?p=0&f=name=DCVupdateAvanceContractuelRAJ&f=activationState=ENABLED',
    
	
	//### BONITA EXTAPI
	
	'urlGetDossiersControlesRAJByProjet': urlHost + '/bonita/API/extension/avancesRaj?p=0&c=10000&numeroProjet={0}',
	'urlGetUserInfos': urlHostApi + '/bonita/API/extension/userInfo',
    'urlGetHistoriqueAnomaliesRaj': urlHostApi + '/bonita/API/extension/anomaliesRaj?p=0&c=10000',
	'urlGetVentilationRubrique': urlHostApi + '/bonita/API/extension/getVentilationRubriqueRemboursement?p=0&c=10000&idDr={0}',
    'urlGetAccessObjectBdm': urlHostApi + '/bonita/API/extension/getObjectAccess?numeroProjet={0}',
	'urlGetTachesDCV': urlHostApi + '/bonita/API/extension/tasksDCV?p=0&c=1000',
    'urlAffecteTaks': urlHostApi + '/bonita/API/extension/assignTasksToUser?p=0&c=1&loginNewUser={0}',
	'urlUnassignTasks2ndNiv': urlHostApi + '/bonita/API/extension/unassignTaskByDeletedUser?p=0&c=10&loginUser={0}',
    'urlAssignUnassignTasksAfdPro': urlHostApi + '/bonita/API/extension/assignUnassignTasksAfdPro?p=0&c=10&loginUser={0}',
    'urlGetHistoriqueAvancesContractuelRaj': urlHostApi + '/bonita/API/extension/avancesContractuelsRaj?p=0&c=10000',
    'urlGetMontantVueProjetConcours': urlHostApi + '/bonita/API/extension/getMontantVueProjetConcours?numeroProjet={0}&entite={1}',
    'urlGetMontantVueConcours': urlHostApi + '/bonita/API/extension/getMontantVueConcours?numeroConcours={0}&entite={1}&deviseConcours={2}',
	'urlGetAnomaliesByProject': urlHost + '/bonita/API/extension/fr.afd.newV.Anomalie?q=findByNumero_projet&p=0&c=10000&f=numero_projet={0}',
	
	//### BONITA BUSINESS DATA
	
	'urlGetCountDdrByIdAvanceContractuel': urlHostApi + '/bonita/API/bdm/businessData/fr.afd.newV.DossierReglement?q=countDdrForFindById_avance_contractuel&p=0&c=1&f=id_avance_contractuel={0}',
	'urlGetAvancesByConcours': urlHost + '/bonita/API/bdm/businessData/fr.afd.newV.AvanceContractuel?q=findByNumero_concours&p=0&c=10000&f=numero_concours={0}',
    'urlGetAvancesByProjet': urlHost + '/bonita/API/bdm/businessData/fr.afd.newV.AvanceContractuel?q=findByNumero_projet&p=0&c=10000&f=numero_projet={0}',
    'urlGetAvance': urlHost + '/bonita/API/bdm/businessData/fr.afd.newV.AvanceContractuel?q=findByPersistenceId&p=0&c=10000&f=persistenceId={0}',
    'urlGetVersements': urlHost + '/bonita/API/bdm/businessData/fr.afd.newV.DossierVersement?q=findByEntite&p=0&c=10000&f=entite={0}',
	'urlGetVersement': urlHost + '/bonita/API/bdm/businessData/fr.afd.newV.DossierVersement?q=findByPersistenceId&p=0&c=1&f=persistenceId={0}',
	'urlGetAllAnomaliesByCaseIdDossier': urlHostApi + '/bonita/API/bdm/businessData/fr.afd.newV.Anomalie?q=findAnomalieByCaseIdDossier&p=0&c=1000&f=case_id_dossier={0}',
    'urlGetVersementByNumero': urlHost + '/bonita/API/bdm/businessData/fr.afd.newV.DossierVersement?q=findByNumero_dossier_versement&p=0&c=1&f=numero_dossier_versement={0}',
    'urlGetVersementsByNumProjet': urlHost + '/bonita/API/bdm/businessData/fr.afd.newV.DossierVersement?q=findByNumero_projet&p=0&c=1000&f=numero_projet={0}',
    'urlGetReglementByCaseId2NdNiv': urlHost + '/bonita/API/bdm/businessData/fr.afd.newV.DossierReglement?q=findByCase_id_2nd_niv&p=0&c=1&f=case_id_2nd_niv={0}',
    'urlGetReglement': urlHost + '/bonita/API/bdm/businessData/fr.afd.newV.DossierReglement?q=findByPersistenceId&p=0&c=1&f=persistenceId={0}',
    'urlGetReglementsByNumVersement': urlHost + '/bonita/API/bdm/businessData/fr.afd.newV.DossierReglement?q=findByNumero_dossier_versement&p=0&c=1000&f=numero_dossier_versement={0}',
    'urlGetReglementByCaseId2ndNiveau': urlHost + '/bonita/API/bdm/businessData/fr.afd.newV.DossierReglement?q=findByCase_id_2nd_niv&p=0&c=1&f=case_id_2nd_niv={0}',
    'urlGetReglementsByNumProjet': urlHost + '/bonita/API/bdm/businessData/fr.afd.newV.DossierReglement?q=findByNumero_projet&p=0&c=1000&f=numero_projet={0}',
	'urlGetReglements': urlHost + '/bonita/API/bdm/businessData/fr.afd.newV.DossierReglement?q=findByEntite&p=0&c=10000&f=entite={0}',
    'urlGetJustificatifsByNumVersement': urlHost + '/bonita/API/bdm/businessData/fr.afd.newV.JustificatifsDossierVersement?q=findByNumero_dossier_versement&p=0&c=1000&f=numero_dossier_versement={0}',
    'urlGetDemandeFixationTaux': urlHost + '/bonita/API/bdm/businessData/fr.afd.newV.DemandeFixationTaux?q=findByNumero_concours&p=0&c=1&f=numero_concours={0}',
	'urlGetCommentaires': urlHost + '/bonita/API/bdm/businessData/fr.afd.ref.Commentaires?q=findByPersistanceIdParentObject&p=0&c=10000&f=persistanceIdParentObject={0}',
    'urlGetCommentairesByNumero': urlHost + '/bonita/API/bdm/businessData/fr.afd.ref.Commentaires?q=findByTypePartentObject&p=0&c=10000&f=typePartentObject={0}',
    'urlGetControles': urlHost + '/bonita/API/bdm/businessData/fr.afd.newV.ControleAfdPro?q=findByParentObjectCaseId&p=0&c=10000&f=parentObjectCaseId={0}',
    'urlGetControleById': urlHost + '/bonita/API/bdm/businessData/fr.afd.newV.ControleAfdPro?q=findByPersistenceId&p=0&c=1&f=persistenceId={0}',
    'urlGetControleByParentCodeAndId': urlHost + '/bonita/API/bdm/businessData/fr.afd.newV.ControleAfdPro?q=findByCodeControleAndParentObjectPersistenceId&p=0&c=1&f=code_controle={0}&f=parentObjectPersistenceId={1}',
    'urlGetfixationTaux': urlHost + '/bonita/API/bdm/businessData/fr.afd.newV.DemandeFixationTaux?q=findByNumConcoursAndNumDossierVersementAndNumDossierReglement&p=0&c=1000&f=numero_concours={0}&f=numero_dossier_versement={1}&f=numero_dossier_reglement={2}',
    'urlGetfixationTauxByConcours': urlHost + '/bonita/API/bdm/businessData/fr.afd.newV.DemandeFixationTaux?q=findByConcoursDESC&p=0&c=1000&f=numero_concours={0}',
	'urlGetDocumentsContractuel': urlHost + '/bonita/API/bdm/businessData/fr.afd.newV.DocumentContractuel?q=findByNumero_projet&p=0&c=10000&f=numero_projet={0}',
    'urlGetDoContractuelById': urlHost + '/bonita/API/bdm/businessData/fr.afd.newV.DocumentContractuel?q=findByPersistenceId&p=0&c=10000&f=persistenceId={0}',
    'urlGetAvanceContractuel': urlHost + '/bonita/API/bdm/businessData/fr.afd.newV.AvanceContractuel?q=findByPersistenceId&p=0&c=1&f=persistenceId={0}',
    'urlGetJustificatifRemboursement': urlHost + '/bonita/API/bdm/businessData/fr.afd.newV.JustificatifRemboursement?q=findByPersistenceId&p=0&c=1&f=persistenceId={0}',
    'urlGetJustifsRembByIdAvanceContractuel': urlHost + '/bonita/API/bdm/businessData/fr.afd.newV.JustificatifRemboursement?q=findById_avance_contractuel&p=0&c=1000&f=id_avance_contractuel={0}',
    'urlGetAvanceContractuels': urlHost + '/bonita/API/bdm/businessData/fr.afd.newV.AvanceContractuel?q=findByNumero_projet&p=0&c=10000&f=numero_projet={0}',
    'urlGetAvancesContractuel': urlHost + '/bonita/API/bdm/businessData/fr.afd.newV.AvanceContractuel?q=find&p=0&c=100000',
    'urlGetDocumentContractuelById': urlHost + '/bonita/API/bdm/businessData/fr.afd.newV.DocumentContractuel?q=findByPersistenceId&p=0&c=1&f=persistenceId={0}',
    'urlGetMontantJustificatifRubriqueById': urlHost + '/bonita/API/bdm/businessData/fr.afd.newV.MontantJustificatifRubrique?q=findById_rubrique&p=0&c=1&f=id_rubrique={0}',
	'urlGetJustificatifsByIdDcAnIdDdr': urlHost + '/bonita/API/bdm/businessData/fr.afd.newV.JustificatifReglement?q=findById_document_contractuelAndId_reglement&p=0&c=100&f=id_document_contractuel={0}&f=id_dossier_reglement={1}',
    'urlGetJustificatifsByIdDdr': urlHost + '/bonita/API/bdm/businessData/fr.afd.newV.JustificatifReglement?q=findById_dossier_reglement&p=0&c=1000&f=id_dossier_reglement={0}',
    'urlGetNotifications': urlHost + '/bonita/API/bdm/businessData/fr.afd.ref.NotificationMail?q=findByPersistanceIdParentObject&p=0&c=10000&f=persistanceIdParentObject={0}',
    'urlGetNotifications2NdNiv': urlHost + '/bonita/API/bdm/businessData/fr.afd.ref.NotificationMail?q=findByCaseIdParentObject&p=0&c=10000&f=caseIdParentObject={0}',
    'urlGetAnomalie': urlHost + '/bonita/API/bdm/businessData/fr.afd.newV.Anomalie?q=findByPersistenceId&p=0&c=1&f=persistenceId={0}',
    'urlGeSommeDDRByDCAndStatut': urlHost + '/bonita/API/bdm/businessData/fr.afd.newV.DossierReglement?q=sommeDDRByDCAndStatut&p=0&c=1&f=entite={0}&f=id_document_contractuel={1}&f=statut={2}',
    'urlSommeDDRStatutEnCours': urlHost + '/bonita/API/bdm/businessData/fr.afd.newV.DossierReglement?q=sommeDDRAFDStatutEnCours&p=0&c=1&f=numero_concours={0}',
    'urlCountDDRStatutNonAnnuleByNumVersement': urlHost + '/bonita/API/bdm/businessData/fr.afd.newV.DossierReglement?q=countDDRStatutNonAnnuleByNumVersement&p=0&c=1&f=numero_dossier_versement={0}',
    'urlGetNotificationsByTypeAndPersistanceIdParentObject': urlHost + '/bonita/API/bdm/businessData/fr.afd.ref.NotificationMail?q=findByTypeNotificationAndPersistanceIdParentObject&p=0&c=10000&f=persistanceIdParentObject={0}&f=typeNotification={1}',
    'urlGetCriteresRisqueByDDR': urlHost + '/bonita/API/bdm/businessData/fr.afd.newV.ControleAfdPro?q=getNatureCritereRisqueByDDR&p=0&c=10000&f=persistenceIdDDR={0}',
    'urlGetCountDDRsByNumeroConcours': urlHost + '/bonita/API/bdm/businessData/fr.afd.newV.DossierReglement?q=countForFindByNumero_concours&p=0&c=1&f=numero_concours={0}',
	'urlGetAvanceRAJDefaultByPersistenceId': urlHost + '/bonita/API/bdm/businessData/fr.afd.newV.AvanceContractuelControleRAJ?q=findByPersistenceId&p=0&c=1&f=persistenceId={0}',
    'urlGetAvanceRAJZero': urlHost + '/bonita/API/bdm/businessData/fr.afd.newV.AvanceContractuelControleRAJ?q=findByCase_id_raj_zero&p=0&c=1&f=case_id_raj_zero={0}',
    'urlGetAvanceRAJDefaut': urlHost + '/bonita/API/bdm/businessData/fr.afd.newV.AvanceContractuelControleRAJ?q=findByCase_id_raj_default&p=0&c=1&f=case_id_raj_default={0}',
    'urlGetAvanceFigeeByIdDrAndIdAvance': urlHost + '/bonita/API/bdm/businessData/fr.afd.newV.AvanceFigee?q=findAvanceFigeeByIdDrAndIdAvance&p=0&c=1&f=id_dossier_reglement={0}&f=id_avance_contractuel={1}',
    'urlDDRsEnCoursByConcours': urlHost + '/bonita/API/bdm/businessData/fr.afd.newV.DossierReglement?q=findDDRAFDStatutEnCours&p=0&c=10000&f=numero_concours={0}',
    'urlGetTiersUsedByConcours': urlHost + '/bonita/API/bdm/businessData/fr.afd.newV.ConcoursTiers?q=findByNumeroConcours_typeParentObject&p=0&c=10000&f=numero_concours={0}&f=type_parent_object={1}&f=entite={2}',
    'urlGetConcourTiersById': urlHost + '/bonita/API/bdm/businessData/fr.afd.newV.ConcoursTiers?q=findByNumeroConcours_idTiers_typeParentObject&p=0&c=1&f=numero_concours={0}&f=id_tiers={1}&f=type_parent_object={2}&f=entite={3}',
    'urlGetCountConcoursBdm': urlHost + '/bonita/API/bdm/businessData/fr.afd.newV.ConcoursBdm?q=countForFindNumeroConcoursAndCaseId&p=0&c=1&f=numero_concours={0}&f=ctl_case_id={1}',   
    'urlGetConcoursBdm': urlHost + '/bonita/API/bdm/businessData/fr.afd.newV.ConcoursBdm?q=findByNumero_concours&p=0&c=10000&f=numero_concours={0}',	
	'urlGetSsrub1ByPersistenceId': urlHost + '/bonita/API/bdm/businessData/fr.afd.newV.SsRubL1?q=findByPersistenceId&p=0&c=1&f=persistenceId={0}',
    'urlGetSsrub2ByPersistenceId': urlHost + '/bonita/API/bdm/businessData/fr.afd.newV.SsRub2?q=findByPersistenceId&p=0&c=1&f=persistenceId={0}',
    'urlGetSsrub2ByPersistenceId': urlHost + '/bonita/API/bdm/businessData/fr.afd.newV.SsRubL3?q=findByPersistenceId&p=0&c=1&f=persistenceId={0}',
    'urlGetRubriqueByPersistenceId': urlHost + '/bonita/API/bdm/businessData/fr.afd.newV.Rubrique?q=findByPersistenceId&p=0&c=1&f=persistenceId={0}',
	
	//# API serviceBDM
	
	'urlGetAuthorization': urlHost + '/app/v1/servicesBdm/web/bdm/',
	'urlGetHistoriqueAnomalies': urlHostApi + '/app/v1/servicesBdm/web/bdm/dcv/anomalie/unitaire',
	'urlGetAnomaliesAllByproject': urlHostApi + '/app/v1/servicesBdm/web/bdm/dcv/anomalie/projet/{0}',
	'urlGetHistoriqueDossiers': urlHostApi + '/app/v1/servicesBdm/web/bdm/dcv/dr/controle',
    'urlGetPilotageDDR': urlHostApi + '/app/v1/servicesBdm/web/bdm/controleDossierEligible',
	'urlUpdateDdrUser2ndNiv': urlHostApi + '/app/v1/servicesBdm/web/bdm/update2ndNivDdrUser?vpersistenceid={0}&vidutilisateur={1}',
	'urlGetPilotageDCV': urlHostApi + '/app/v1/servicesBdm/web/bdm/pilotageDcv',
    'urlGetVolumetriesDVEtDDR': urlHostApi + '/app/v1/servicesBdm/web/bdm/volumetrieDdrEtDv',
    'urlGetVolumetriesCtlUnitAnos': urlHostApi + '/app/v1/servicesBdm/web/bdm/volumetrieDcvCtlUnitAnomalie',
    'urlGetVolumetriesCtlUnitDossiers': urlHostApi + '/app/v1/servicesBdm/web/bdm/volumetrieDcvCtlUnitDossier',
    'urlGetVolumetriesControleRAJDossier': urlHostApi + '/app/v1/servicesBdm/web/bdm/volumetrieControleRajDC',
    'urlGetVolumetriesControleRAJAnomalie': urlHostApi + '/app/v1/servicesBdm/web/bdm/volumetrieControleRajAnomalie',
    'urlGetReportingListeAvance': urlHostApi + '/app/v1/servicesBdm/web/bdm/listeAvances',
	'urlGetListePaiementTiers': urlHostApi + '/app/v1/servicesBdm/web/bdm/listePaiementTiers',
    'urlGetListePaiementDocContractuel': urlHostApi + '/app/v1/servicesBdm/web/bdm/listePaiementDocumentContractuel',
	'urlGetVersementsByEntite': urlHost + '/app/v1/servicesBdm/web/bdm/user/dossierVersement',
	'urlGetAllReglements': urlHost + '/app/v1/servicesBdm/web/bdm/listeVersement',
	'urlGetIdConcours': urlHost + '/app/v1/servicesBdm/web/bdm/dossierReglement/concours',
    'urlGetIdProjets': urlHost + '/app/v1/servicesBdm/web/bdm/dossierVersement/projet',
    'urlGetAudit': urlHost + '/app/v1/servicesBdm/web/bdm/pisteAudit',
    'urlGetDdrPdfFinal': urlHost + '/app/v1/servicesBdm/web/bdm/downloadFile?persistenceId={0}',
    'urlGetConcoursRaj': urlHost + '/app/v1/servicesBdm/web/bdm/concoursRaj',
    'urlGetDossiersControlesByProjet': urlHost + '/app/v1/servicesBdm/web/bdm/dcv/dossiercontrole/projet/{0}',
	'urlGetDCByTiers': urlHost + '/app/v1/servicesBdm/web/bdm/dcByTiers',
    'urlGetConcoursRav': urlHost + '/app/v1/servicesBdm/web/bdm/concoursRav',
    'urlGetRemboursementsReporting': urlHost + '/app/v1/servicesBdm/web/bdm/remboursements',
    //'urlGetArchivedCaseDocuments': urlHost + '/bonita/API/bpm/archivedCaseDocument?p=0&c=100&f=caseId={0}&o=creationDate%20DESC',
    'urlGetArchivedCaseDocuments': urlHost + '/app/v1/servicesBdm/web/bdm/downloadPdfIntermediaire?persistenceId={0}',
	
	//# API APIREF
	
	'urlGetProjetByNum': urlHostApi + '/app/v1/apiref/web/referentiel/siop/projets?filtre=numero_projet&value={0}',
    'urlGetProjets': urlHostApi + '/app/v1/apiref/web/referentiel/siop/projets/siop',
    'urlGetProjetsByEntiteAndUserId': urlHostApi + '/app/v1/apiref/web/referentiel/siop/projet/user?entite={0}',
    // 'urlGetProjetsByEntiteAndUserId': urlHostApi + '/app/v1/apiref/referentiel/siop/projet/user?entite={0}&userId={1}',
    'urlGetProjetsNewDVPro': urlHostApi + '/app/v1/apiref/web/referentiel/siop/pro/dv/new/projet/user',
    // 'urlGetProjetsByEntite': urlHostApi + '/app/v1/apiref/referentiel/siop/projet/user?entite={0}&userId={1}',
    'urlGetProjetsByEntite': urlHostApi + '/app/v1/apiref/web/referentiel/siop/projet/user?entite={0}',
    'urlGetAllProjets': urlHostApi + '/app/v1/apiref/web/referentiel/siop/projets/siop',
    //'urlGetConcoursByUser': urlHostApi + '/app/v1/apiref/referentiel/siop/projet/concours/user',
    'urlGetConcoursSIOPByNumero': urlHostApi + '/app/v1/apiref/web/referentiel/siop/projet/concours/{0}',
    'urlGetConcoursNewDVAfd': urlHostApi + '/app/v1/apiref/web/referentiel/siop/afd/dv/new/concours/user',
    'urlGetCritresRisquesConcours': urlHostApi + '/app/v1/apiref/web/referentiel/siop/projet/critereRisque/concours',
    'urlGetCritresRisquesProjet': urlHostApi + '/app/v1/apiref/web/referentiel/siop/projet/critereRisque/projet',

    'urlGetConcoursGCFByNumero': urlHostApi + '/app/v1/apiref/web/referentiel/gcf/ConcoursGcf/{0}',
    'urlGetConcoursGCFByUserWithRAV': urlHostApi + '/app/v1/apiref/web/referentiel/gcf/projet/concours/user',
    'urlGetAllConcoursGCF': urlHostApi + '/app/v1/apiref/web/referentiel/gcf/ConcoursGcfs',
    'urlGetConcoursGCFByProjet': urlHostApi + '/app/v1/apiref/web/referentiel/gcf/projet/concoursGcf/{0}',

	'urlGetOperations': urlHostApi + '/app/v1/apiref/web/referentiel/nomenclatures/operations',    
	'urlGetProduitsFinancier': urlHostApi + '/app/v1/apiref/web/referentiel/nomenclatures/produits',
    'urlGetTypesJustificatif': urlHostApi + '/app/v1/apiref/web/referentiel/nomenclatures/typesJustificatif',
    'urlGetDevises': urlHostApi + '/app/v1/apiref/web/referentiel/nomenclatures/devises',
    'urlGettypeMarches': urlHostApi + '/app/v1/apiref/web/referentiel/nomenclatures/typeMarches',
    'urlGetPays': urlHostApi + '/app/v1/apiref/web/referentiel/nomenclatures/pays',    
	'urlGetPilotagePerimetresAgencesUnused': urlHostApi + '/app/v1/apiref/web/referentiel/nomenclatures/agencesNonAffecte',
    'urlGetPilotagePerimetresDivisionssUnused': urlHostApi + '/app/v1/apiref/web/referentiel/nomenclatures/divisionNonAffecte',
    'urlGetPilotagePerimetresOperationsUnused': urlHostApi + '/app/v1/apiref/web/referentiel/nomenclatures/operationsNonAffecte',
    'urlGetAgences': urlHostApi + '/app/v1/apiref/web/referentiel/nomenclatures/agencesGestions',
    'urlGetFamillesProduits': urlHostApi + '/app/v1/apiref/web/referentiel/nomenclatures/famillesProduits',
    'urlGetDivisions': urlHostApi + '/app/v1/apiref/web/referentiel/nomenclatures/DivisionsServices',
    'urlGetDivisionsBySociete': urlHostApi + '/app/v1/apiref/web/referentiel/nomenclatures/DivisionsServices/{0}',
    'urlGetDivisionsBySocieteAFD': urlHostApi + '/app/v1/apiref/web/referentiel/nomenclatures/DivisionsServices/C',
    'urlGetDirectionsRegionales': urlHostApi + '/app/v1/apiref/web/referentiel/nomenclatures/directionsRegionales',

    'urlGetModalitesPaiement': urlHostApi + '/app/v1/apiref/web/referentiel/ref/modalitesPaiements',
	'urlGetModalitesPaiementPROPARCO': urlHostApi + '/app/v1/apiref/web/referentiel/ref/modalitesPaiements/PROPARCO',
    'urlGetModalitesPaiementAFD': urlHostApi + '/app/v1/apiref/web/referentiel/ref/modalitesPaiements/AFD',
    'urlGetTypesVersement': urlHostApi + '/app/v1/apiref/web/referentiel/ref/typeVersementsRef',
    'urlGetComptesKtp': urlHostApi + '/app/v1/apiref/web/referentiel/ref/compteKTP',
    'urlGetNatureMarche': urlHostApi + '/app/v1/apiref/web/referentiel/ref/natureMarche',
    'urlGetPilotagePerimetresModalitesUnused': urlHostApi + '/app/v1/apiref/web/referentiel/ref/modalitesNonAffecte',    
	'urlGetTypeAmortissement': urlHostApi + '/app/v1/apiref/web/referentiel/ref/typeAmortissements',
    'urlGetTypeRessources': urlHostApi + '/app/v1/apiref/web/referentiel/ref/typeRessources',
    'urlGetTypeAts': urlHostApi + '/app/v1/apiref/web/referentiel/ref/typeAts', 
    
	'urlGetBeneficiairesMin': urlHostApi + '/app/v1/apiref/web/referentiel/irisa/tiers/min',
    'urlGetBeneficiaireById': urlHostApi + '/app/v1/apiref/web/referentiel/irisa/tiers/{0}',
    'urlGetBeneficiairesAdresse': urlHostApi + '/app/v1/apiref/web/referentiel/irisa/tiers/adresses',
    'urlGetBeneficiairesAdresseWithBank': urlHostApi + '/app/v1/apiref/web/referentiel/irisa/tiers/newDr',
    
	'urlCTX': urlHost + '/app/v1/apiref/web/ctx/coursDevises?date_valeur={0}&devise_cotation={1}&devise_reference={2}',
	
	//# API ORGA
	
	'urlGetUserContext': urlHostParam + '/app/v1/organisation/web/orga/utilisateur',
    'urlGetUsers': urlHostParam + '/app/v1/organisation/web/orga/utilisateurs/all',
    'urlUpdateUser': urlHostParam + '/app/v1/organisation/web/orga/admin/utilisateur',
    'urlGetEntites': urlHostParam + '/app/v1/organisation/web/orga/entitesOrga',
    'urlGetRoles': urlHostParam + '/app/v1/organisation/web/orga/roles',
	'urlGetDestinatairesAFD': urlHostParam + '/app/v1/organisation/web/orga/actors/afd?idActeurInitial={0}&roleCible={1}&numProjet={2}',
    'urlGetDestinatairesPROPARCO': urlHostParam + '/app/v1/organisation/web/orga/actors/proparco/filtre?acteurInitial={0}&roleCible={1}&numeroProjet={2}',
    'urlGetPilotagePerimetres': urlHostParam + '/app/v1/organisation/web/orga/controleursDCV',
    'urlSetPilotagePerimetre': urlHostParam + '/app/v1/organisation/web/orga/controleurDCV',
	'urlGetEntitesOrgaByType': urlHost + '/app/v1/organisation/web/orga/entiteOrga/type/{0}',
    'urlGetEntitesOrgaByParent': urlHost + '/app/v1/organisation/web/orga/entiteOrga/parent/{0}/{1}',
    'urlGetEntiteOrgaTypes': urlHost + '/app/v1/organisation/web/orga/entitesOrga/type',
    'urlSetEntiteOrga': urlHost + '/app/v1/organisation/web/orga/entiteOrga',
	'urlDeleteEntiteOrga': urlHost + '/app/v1/organisation/web/orga/entiteOrga/delete?codeEntiteOrga={0}&typeEntiteOrga={1}',
//	'urlGetEntiteOrgaByCode': urlHostApi + '/api/organisation/entiteOrga/{0}',
//   'urlGetDirectionsRegionale': urlHostApi + '/api/organisation/entiteOrga/type/DIRECTION REGIONALE',
//    'urlGetMemberProjet': urlHostParam + '/api/organisation/isMemberProjetProparco?idUtilisateur={0}&numeroProjet={1}',
	
	//# API PARAM
	
	'urlGetParamControles': urlHostParam + '/app/v1/param/web/regle/controles/{0}',
    'urlGetParamControlesAll': urlHostParam + '/app/v1/param/web/regle/controles',
    'urlAddParamControle': urlHostParam + '/app/v1/param/web/regle/controle',
    'urlGetParamControle': urlHostParam + '/app/v1/param/web/regle/controle/{0}',
    'urlSetParamControle': urlHostParam + '/app/v1/param/web/regle/controle/{0}',

    'urlGetEtapes': urlHostParam + '/app/v1/param/web/regle/etapes/{0}',
    
    'urlGetReglesAuto': urlHostParam + '/app/v1/param/web/regle/regles/entite/{0}',

    'urlGetParamAnomalies': urlHostParam + '/app/v1/param/web/regle/anomalies',
    'urlGetAnomalieByCode': urlHostParam + '/app/v1/param/web/regle/anomalieByCode/{0}',
    'urlGetParamAnomaliesUnused': urlHostParam + '/app/v1/param/web/regle/unusedAnomalies',
    'urlAddAnomalie': urlHostParam + '/app/v1/param/web/regle/anomalie',
    'urlUpdateAnomalie': urlHostParam + '/app/v1/param/web/regle/anomalie/{0}',

    'urlGetParamThemes': urlHostParam + '/app/v1/param/web/regle/themes',
    'urlGetThemes': urlHostParam + '/app/v1/param/web/regle/themes/{0}',
    'urlAddTheme': urlHostParam + '/app/v1/param/web/regle/theme',
    'urlUpdateTheme': urlHostParam + '/app/v1/param/web/regle/theme/{0}',

    'urlGetControleFiltreCriteres': urlHostParam + '/app/v1/param/web/regle/criteres/entite/{0}',
    'urlGetParamCriteres': urlHostParam + '/app/v1/param/web/regle/criteresEligibilite/{0}',
    'urlUpdateParamCriteres': urlHostParam + '/app/v1/param/web/regle/critereEligibilite/{0}',
    'urlDeleteParamCritere': urlHostParam + '/app/v1/param/web/regle/critereEligibilite/delete/{0}',
    'urlAddParamCritere': urlHostParam + '/app/v1/param/web/regle/critereEligibilite/',	

	'urlGetPilotageAffectations': urlHostApi + '/app/v1/param/web/application/parametrageApplication/DCV',
    'urlSetPilotageAffectations': urlHostApi + '/app/v1/param/web/application/parametrageApplication/DCV',

	'urlHabilitationsByUserId': urlHostApi + '/app/v1/param/web/habilitation/habilitation/{0}',
    'urlHabilitationsAdmin': urlHost + '/app/v1/param/web/habilitation/habilitations',

	//# AUTH INWEBO
    'urlCheckInwebo': urlHost + '/app/v1/auth/web/inwebo/auth?userId={0}',
	
};